### ISSUE TITLE
dashboard 可以分享下吗

### ISSUE THREAD

**Issue by chanwoood** [BigBrotherTrade/trader#1]
安装好依赖后，我尝试使用 `python trader/main.py` 运行程序，结果报错：
```
Traceback (most recent call last):
  File "/root/trader-master/trader/main.py", line 27, in <module>
    django.setup()
  File "/root/trader-master/lib/python3.11/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/trader-master/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/root/trader-master/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/trader-master/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imvolte/py3113/py/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dashboard'
```
No module named 'dashboard'，我留意到似乎需要这个文件夹：
![image](https://github.com/BigBrotherTrade/trader/assets/22561878/0f4e0e7e-e415-4899-b51c-82cd332849bf)

**Comment by timercrack** [comment]
这是trader模块，只负责交易逻辑，dashboard是单独的一个模块：[https://github.com/BigBrotherTrade/dashboard](url)

**Comment by ylsaker** [comment]
dashboard.settings以及一些django的配置可以分享一下吗？

**Comment by timercrack** [comment]
dashboard的repo里面有
