### ISSUE TITLE
是不是缺少大哥2.2策略？

### ISSUE THREAD

**Issue by qqnr88** [BigBrotherTrade/trader#5]
(venv) [root@iZbp13hsmske2ra9ukl7qnZ trader]# python trader/main.py
Big Brother is watching you!
used config file: /root/.config/trader/config.ini
log stored in: /root/.cache/trader/log
pid file: /root/.cache/trader/trader.pid
Traceback (most recent call last):
  File "/root/trader/trader/main.py", line 77, in <module>
    TradeStrategy(name='大哥2.2').run()
  File "/root/trader/trader/strategy/brother2.py", line 45, in __init__
    self.__strategy = Strategy.objects.get(name=name)
  File "/root/trader/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/trader/venv/lib/python3.10/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
panel.models.DoesNotExist: Strategy matching query does not exist.

**Comment by xjf01793** [comment]
@qqnr88 我也碰到类似的问题，请教一下你是怎么解决这个问题的？

**Comment by johnxn** [comment]
得把dashboard搭起来，进入后台自己新建一个策略

**Comment by 827346462** [comment]
> 得把dashboard搭起来，进入后台自己新建一个策略

我看这个dashboard是没有界面的，后台的策略是访问的数据库。是我理解错了吗，烦请具体解答一下。

**Comment by qqnr88** [comment]
> > 得把dashboard搭起来，进入后台自己新建一个策略
> 
> 我看这个dashboard是没有界面的，后台的策略是访问的数据库。是我理解错了吗，烦请具体解答一下。

 dashboard搭建起来了 进去看了下 功能简单  策略也不知道怎么写啊  最好有个现成的策略可以参考下

**Comment by qqnr88** [comment]
> > 得把dashboard搭起来，进入后台自己新建一个策略
> 
> 我看这个dashboard是没有界面的，后台的策略是访问的数据库。是我理解错了吗，烦请具体解答一下。

 dashboard搭建起来了 进去看了下 功能简单  策略也不知道怎么写啊  最好有个现成的策略可以参考下

**Comment by 827346462** [comment]
> > > 得把dashboard搭起来，进入后台自己新建一个策略
> > 
> > 
> > 我看这个dashboard是没有界面的，后台的策略是访问的数据库。是我理解错了吗，烦请具体解答一下。
> 
> dashboard搭建起来了 进去看了下 功能简单 策略也不知道怎么写啊 最好有个现成的策略可以参考下

请问dashboard 的运行是怎么弄的呀，账户密码不怎么怎么输入，在auth_user数据库里面写入也不行

**Comment by InvisibleLeVen** [comment]
同这个问题，mysql数据库中还需要panel_strategy表，表啥样也不清楚。。作者开的不是很源

**Comment by johnxn** [comment]
策略都在brother2.py这个文件里面，双均线+突破，一个经典的趋势跟踪策略，具体可以看下《趋势交易》这本书。我们需要自己提供策略的参数

**Comment by dick129418** [comment]
> 策略都在brother2.py这个文件里面，双均线+突破，一个经典的趋势跟踪策略，具体可以看下《趋势交易》这本书。我们需要自己提供策略的参数

策略是哪个函数呢,感觉都是交易或者交易信息相关的函数

**Comment by mdq1005** [comment]
> 策略都在brother2.py这个文件里面，双均线+突破，一个经典的趋势跟踪策略，具体可以看下《趋势交易》这本书。我们需要自己提供策略的参数


你好是不是这本书叫 趋势交易法

**Comment by bluemeteorolite** [comment]
> 同这个问题，mysql数据库中还需要panel_strategy表，表啥样也不清楚。。作者开的不是很源

在dashboard目录下运行 python manage.py migrate

**Comment by bluemeteorolite** [comment]
> (venv) [root@iZbp13hsmske2ra9ukl7qnZ trader]# python trader/main.py Big Brother is watching you! used config file: /root/.config/trader/config.ini log stored in: /root/.cache/trader/log pid file: /root/.cache/trader/trader.pid Traceback (most recent call last): File "/root/trader/trader/main.py", line 77, in TradeStrategy(name='大哥2.2').run() File "/root/trader/trader/strategy/brother2.py", line 45, in **init** self.__strategy = Strategy.objects.get(name=name) File "/root/trader/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/root/trader/venv/lib/python3.10/site-packages/django/db/models/query.py", line 649, in get raise self.model.DoesNotExist( panel.models.DoesNotExist: Strategy matching query does not exist.

帅锅，请问你的trader/config.ini模版在哪里拿的 谢谢

**Comment by mdq1005** [comment]
config.ini 有模版示例吗

**Comment by vincentqin-sys** [comment]
有没有合约列表的初始化脚本？项目跑起来后，需要手工把所有合约都维护近表里吗？
